"""Module 2 — direct parsing path (typed documents).

Responsibility: read text that is already digital, with no recognition step,
so raw_conf is 1.0 for every page:
- PDF: the embedded text layer (pdfplumber), one entry per page; ruled tables are found
  (find_tables) and written as table rows where they appear on the page
- DOCX: paragraphs and tables in document order, split into pages where Word
  broke pages when it last saved the file (w:lastRenderedPageBreak) and at
  manual page breaks. A file never laid out by Word (e.g. generated by a
  script) has no such marks and stays one entry.
- PPTX: one entry per slide (text boxes, tables, grouped shapes)
- TXT: the whole file as one entry

Tables (Word, PowerPoint, and ruled tables in PDFs) keep their header with every
row, so each row can be understood on its own, also after chunking splits a long table:

    Table: Month | Sales | Customers
    Month: Jan | Sales: 50,000 | Customers: 200

A table without a usable header row (one row, empty or repeated header cells) is
written as plain rows: "a | b | c". content_type.py (Module 4) labels these lines as table.

Uses from schemas.py: nothing directly; output feeds chunker.py -> RecognizedChunk.
"""

import zipfile

import pdfplumber
from docx import Document as open_docx
from docx.opc.exceptions import PackageNotFoundError as DocxPackageError
from docx.table import Table as DocxTable
from docx.text.paragraph import Paragraph
from pptx import Presentation
from pptx.enum.shapes import MSO_SHAPE_TYPE
from pptx.exc import PackageNotFoundError as PptxPackageError

from app.modules.file_types import FileKind, UnreadableFileError, kind_of

TYPED_CONFIDENCE = 1.0
CELL_SEPARATOR = " | "
TABLE_PREFIX = "Table: "

_BROKEN_PACKAGE = (DocxPackageError, PptxPackageError, zipfile.BadZipFile, KeyError, ValueError)


def parse(file_path: str) -> list[tuple[str, float]]:
    """Return (page_text, raw_conf=1.0) per page for any typed file kind."""
    kind = kind_of(file_path)
    if kind is FileKind.DOCX:
        return parse_docx(file_path)
    if kind is FileKind.PPTX:
        return parse_pptx(file_path)
    if kind is FileKind.TXT:
        return parse_txt(file_path)
    return parse_pdf(file_path)


def parse_pdf(file_path: str) -> list[tuple[str, float]]:
    """Return (page_text, raw_conf=1.0) for each page; pages without text give ""."""
    with pdfplumber.open(file_path) as pdf:
        return [(_pdf_page_text(page), TYPED_CONFIDENCE) for page in pdf.pages]


def _pdf_page_text(page) -> str:
    """The page's text with each ruled table written as table rows, in reading order.

    extract_text() alone runs a table's columns together (and mixes up cells that wrap
    onto two lines). Tables are found from their ruling lines; the text above, between
    and below them is extracted band by band, so everything stays in page order.
    A table without ruling lines is not detected and stays plain text, as before.
    """
    try:
        tables = sorted(page.find_tables(), key=lambda t: t.bbox[1])
    except Exception:  # noqa: BLE001 - table detection must never lose the page text
        tables = []
    if not tables:
        return (page.extract_text() or "").strip()
    left, top, right, bottom = page.bbox
    parts, y = [], top
    for table in tables:
        t_top, t_bottom = table.bbox[1], table.bbox[3]
        if t_top > y:
            parts.append(page.crop((left, y, right, t_top)).extract_text() or "")
        parts.extend(_grid_lines(table.extract()))
        y = max(y, t_bottom)
    if y < bottom:
        parts.append(page.crop((left, y, right, bottom)).extract_text() or "")
    return "\n".join(part.strip() for part in parts if part and part.strip())


def _clean(text) -> str:
    return " ".join((text or "").split())  # one line: wrapped cell text joined with spaces


HEADER_MAX_WORDS = 5  # a header cell names a column; a longer cell means the row is data


def _usable_header(cells: list[str]) -> bool:
    return (
        len(cells) > 1 and all(cells) and len(set(cells)) == len(cells)
        and all(len(c.split()) <= HEADER_MAX_WORDS for c in cells)
    )


def _grid_lines(grid: list[list]) -> list[str]:
    """Write a table (rows of cell texts; None or "" = empty/merged) as text lines.

    With a usable header row (2+ cells, all filled and different), every data row is
    written as "Header: value | Header: value", so a row still says which value is which
    when it ends up in a chunk without the header.
    """
    rows = [[_clean(c) for c in row] for row in grid]
    rows = [row for row in rows if any(row)]
    if not rows:
        return []
    header, body = rows[0], rows[1:]
    if not _usable_header(header) and len(rows) > 2:
        # A two-row header, e.g. "Criteria | Languages (merged over 3 columns)" above
        # "| C++ | C# | Java": the lower row's names, the upper row's where the lower is empty.
        combined = [low or high for high, low in zip(rows[0], rows[1])]
        if _usable_header(combined):
            header, body = combined, rows[2:]
    if body and _usable_header(header):
        lines = [TABLE_PREFIX + CELL_SEPARATOR.join(header)]
        for row in body:
            pairs = [f"{name}: {value}" for name, value in zip(header, row) if value]
            if pairs:
                lines.append(CELL_SEPARATOR.join(pairs))
        return lines
    return [CELL_SEPARATOR.join(c for c in row if c) for row in rows]


def _cell_texts(row) -> list[str]:
    """A Word/PowerPoint table row's cells, each merged cell once (in its first column)."""
    texts, previous = [], None
    for cell in row.cells:
        element = getattr(cell, "_tc", None)
        if element is not None and element is previous:
            continue  # Word: a cell merged across columns is returned once per column it spans
        previous = element
        if getattr(cell, "is_spanned", False):
            texts.append("")  # PowerPoint: covered by a merged cell to its left/above
            continue
        texts.append(cell.text)
    return texts


def _table_lines(rows) -> list[str]:
    return _grid_lines([_cell_texts(row) for row in rows])


# Where Word ended a page: its own layout mark, a manual page break, or "page break before".
_PAGE_BREAK_XPATH = './/w:lastRenderedPageBreak | .//w:br[@w:type="page"] | .//w:pageBreakBefore'


def parse_docx(file_path: str) -> list[tuple[str, float]]:
    try:
        doc = open_docx(file_path)
    except _BROKEN_PACKAGE as e:
        raise UnreadableFileError(f"not a readable Word document: {e}") from e

    pages: list[list[str]] = [[]]
    # Walk the body in order so tables stay where they appear between paragraphs.
    for block in doc.iter_inner_content():
        # A block containing a break starts a new page (approximate: text before the break
        # inside the same paragraph moves with it). A break on a still-empty page is the same
        # page end marked twice (manual break + Word's layout mark), so it is not counted again.
        if pages[-1] and block._element.xpath(_PAGE_BREAK_XPATH):
            pages.append([])
        if isinstance(block, Paragraph):
            if block.text.strip():
                pages[-1].append(block.text.strip())
        elif isinstance(block, DocxTable):
            pages[-1].extend(_table_lines(block.rows))
    return [("\n".join(lines), TYPED_CONFIDENCE) for lines in pages]


def _shape_lines(shape) -> list[str]:
    if shape.shape_type == MSO_SHAPE_TYPE.GROUP:
        return [line for inner in shape.shapes for line in _shape_lines(inner)]
    if getattr(shape, "has_table", False) and shape.has_table:
        return _table_lines(shape.table.rows)
    if getattr(shape, "has_text_frame", False) and shape.has_text_frame:
        return [p.text.strip() for p in shape.text_frame.paragraphs if p.text.strip()]
    return []


def parse_pptx(file_path: str) -> list[tuple[str, float]]:
    try:
        deck = Presentation(file_path)
    except _BROKEN_PACKAGE as e:
        raise UnreadableFileError(f"not a readable PowerPoint file: {e}") from e
    return [
        ("\n".join(line for shape in slide.shapes for line in _shape_lines(shape)), TYPED_CONFIDENCE)
        for slide in deck.slides
    ]


def parse_txt(file_path: str) -> list[tuple[str, float]]:
    raw = open(file_path, "rb").read()
    if b"\x00" in raw[:4096]:
        raise UnreadableFileError("not a text file (binary content)")
    try:
        text = raw.decode("utf-8-sig")
    except UnicodeDecodeError:
        text = raw.decode("cp1252", errors="replace")  # common for Notepad files saved on Windows
    return [(text.strip(), TYPED_CONFIDENCE)]
