"""Module 2 — direct parsing path (typed documents).

Responsibility: read text that is already digital, with no recognition step,
so raw_conf is 1.0 for every page:
- PDF: the embedded text layer (pdfplumber), one entry per page
- DOCX: paragraphs and tables in document order, split into pages where Word
  broke pages when it last saved the file (w:lastRenderedPageBreak) and at
  manual page breaks. A file never laid out by Word (e.g. generated by a
  script) has no such marks and stays one entry.
- PPTX: one entry per slide (text boxes, tables, grouped shapes)
- XLSX: one entry per worksheet, rows written like table rows
- TXT: the whole file as one entry

Table rows are written with cells separated by two spaces, the same shape
content_type.py (Module 4) recognizes as a table.

Uses from schemas.py: nothing directly; output feeds chunker.py -> RecognizedChunk.
"""

import zipfile

import pdfplumber
from docx import Document as open_docx
from docx.opc.exceptions import PackageNotFoundError as DocxPackageError
from docx.table import Table as DocxTable
from docx.text.paragraph import Paragraph
from pptx import Presentation
from pptx.enum.shapes import MSO_SHAPE_TYPE
from pptx.exc import PackageNotFoundError as PptxPackageError

from app.modules.file_types import FileKind, UnreadableFileError, kind_of

TYPED_CONFIDENCE = 1.0
CELL_SEPARATOR = "  "

_BROKEN_PACKAGE = (DocxPackageError, PptxPackageError, zipfile.BadZipFile, KeyError, ValueError)


def parse(file_path: str) -> list[tuple[str, float]]:
    """Return (page_text, raw_conf=1.0) per page for any typed file kind."""
    kind = kind_of(file_path)
    if kind is FileKind.DOCX:
        return parse_docx(file_path)
    if kind is FileKind.PPTX:
        return parse_pptx(file_path)
    if kind is FileKind.XLSX:
        return parse_xlsx(file_path)
    if kind is FileKind.TXT:
        return parse_txt(file_path)
    return parse_pdf(file_path)


def parse_pdf(file_path: str) -> list[tuple[str, float]]:
    """Return (page_text, raw_conf=1.0) for each page; pages without text give ""."""
    with pdfplumber.open(file_path) as pdf:
        return [((page.extract_text() or "").strip(), TYPED_CONFIDENCE) for page in pdf.pages]


def _row_text(cells: list[str]) -> str:
    # Merged cells repeat the same text in every cell they span; keep it once.
    deduped = [c for i, c in enumerate(cells) if c and (i == 0 or c != cells[i - 1])]
    return CELL_SEPARATOR.join(deduped)


def _table_lines(rows) -> list[str]:
    lines = []
    for row in rows:
        line = _row_text([cell.text.strip().replace("\n", " ") for cell in row.cells])
        if line:
            lines.append(line)
    return lines


# Where Word ended a page: its own layout mark, a manual page break, or "page break before".
_PAGE_BREAK_XPATH = './/w:lastRenderedPageBreak | .//w:br[@w:type="page"] | .//w:pageBreakBefore'


def parse_docx(file_path: str) -> list[tuple[str, float]]:
    try:
        doc = open_docx(file_path)
    except _BROKEN_PACKAGE as e:
        raise UnreadableFileError(f"not a readable Word document: {e}") from e

    pages: list[list[str]] = [[]]
    # Walk the body in order so tables stay where they appear between paragraphs.
    for block in doc.iter_inner_content():
        # A block containing a break starts a new page (approximate: text before the break
        # inside the same paragraph moves with it). A break on a still-empty page is the same
        # page end marked twice (manual break + Word's layout mark), so it is not counted again.
        if pages[-1] and block._element.xpath(_PAGE_BREAK_XPATH):
            pages.append([])
        if isinstance(block, Paragraph):
            if block.text.strip():
                pages[-1].append(block.text.strip())
        elif isinstance(block, DocxTable):
            pages[-1].extend(_table_lines(block.rows))
    return [("\n".join(lines), TYPED_CONFIDENCE) for lines in pages]


def _shape_lines(shape) -> list[str]:
    if shape.shape_type == MSO_SHAPE_TYPE.GROUP:
        return [line for inner in shape.shapes for line in _shape_lines(inner)]
    if getattr(shape, "has_table", False) and shape.has_table:
        return _table_lines(shape.table.rows)
    if getattr(shape, "has_text_frame", False) and shape.has_text_frame:
        return [p.text.strip() for p in shape.text_frame.paragraphs if p.text.strip()]
    return []


def parse_pptx(file_path: str) -> list[tuple[str, float]]:
    try:
        deck = Presentation(file_path)
    except _BROKEN_PACKAGE as e:
        raise UnreadableFileError(f"not a readable PowerPoint file: {e}") from e
    return [
        ("\n".join(line for shape in slide.shapes for line in _shape_lines(shape)), TYPED_CONFIDENCE)
        for slide in deck.slides
    ]


def parse_xlsx(file_path: str) -> list[tuple[str, float]]:
    """One entry per worksheet: each non-empty row's cell values, two spaces apart (a table row)."""
    from openpyxl import load_workbook

    try:
        book = load_workbook(file_path, read_only=True, data_only=True)
    except _BROKEN_PACKAGE + (OSError,) as e:
        raise UnreadableFileError(f"not a readable Excel workbook: {e}") from e
    pages = []
    try:
        for sheet in book.worksheets:
            rows = []
            for row in sheet.iter_rows(values_only=True):
                # Not _row_text: equal neighbouring values are real data here (5, 5), not a merged cell.
                line = CELL_SEPARATOR.join(c for c in ("" if v is None else str(v).strip() for v in row) if c)
                if line:
                    rows.append(line)
            pages.append(("\n".join(rows), TYPED_CONFIDENCE))
    finally:
        book.close()
    return pages


def parse_txt(file_path: str) -> list[tuple[str, float]]:
    raw = open(file_path, "rb").read()
    if b"\x00" in raw[:4096]:
        raise UnreadableFileError("not a text file (binary content)")
    try:
        text = raw.decode("utf-8-sig")
    except UnicodeDecodeError:
        text = raw.decode("cp1252", errors="replace")  # common for Notepad files saved on Windows
    return [(text.strip(), TYPED_CONFIDENCE)]
